export const paths = {
  home: '/',
  auth: { signIn: '/login', resetPassword: '/reset-password' },
  dashboard: {
    overview: '/dashboard',
    account: '/account',
    appointment: '/appointment',
    appointmentDetails: '/appointment/details',
    appointmentDetails_id: (id: string | number) => `/appointment/details/${id}`,
    doctor: '/doctor',
    doctorCreate: '/doctor/create',
    doctorUpdate: (id: string | number) => `/doctor/update/${id}`,
    patient: '/patient',
    specialization: '/specialization',
    qualification: '/qualification',
    symptom: '/symptom',
    integrations: '/integrations',
    settings: '/settings',
    activeRooms: '/activeRooms',
  },
  errors: { notFound: '/not-found' },
} as const;
