export const paths = {
  home: '/',
  auth: { signIn: '/login', resetPassword: '/reset-password', doctorSignup: '/signup-as-doctor', },
  dashboard: {
    overview: '/dashboard',
    account: '/account',
    appointment: '/appointment',
    appointmentDetails: '/appointment/details',
    appointmentDetails_id: (id: string | number) => `/appointment/details/${id}`,
    doctor: '/doctor',
    doctorCreate: '/doctor/create',
    doctorUpdate: (id: string | number) => `/doctor/update/${id}`,
    patient: '/patient',
    specialization: '/specialization',
    qualification: '/qualification',
    symptom: '/symptom',
    integrations: '/integrations',
    //settings: '/settings',  because settings have update password which we don't need
    activeRooms: '/activeRooms',
    user: '/user',
    userCreate: '/user/create',
    userUpdate: (id: string | number) => `/user/update/${id}`,
    salesDashboard: '/sales-dashboard',
    salesDoctor: '/sales-doctor',
    salesDoctorCreate: '/sales-doctor/create',
    salesDoctorUpdate: (id: string | number) => `/sales-doctor/update/${id}`,
  },
  errors: { notFound: '/not-found' },
} as const;
