export const paths = {
  home: '/',
  auth: { signIn: '/login', resetPassword: '/reset-password' },
  dashboard: {
    overview: '/dashboard',
    account: '/dashboard/account',
    appointment: '/dashboard/appointment',
    appointmentDetails: '/dashboard/appointment/details',
    appointmentDetails_id: (id: string | number) => `/dashboard/appointment/details/${id}`,
    doctor: '/dashboard/doctor',
    doctorCreate: '/dashboard/doctor/create',
    doctorUpdate: (id: string | number) => `/dashboard/doctor/update/${id}`,
    patient: '/dashboard/patient',
    specialization: '/dashboard/speciality',
    qualification: '/dashboard/qualification',
    symptom: '/dashboard/symptoms',
    integrations: '/dashboard/integrations',
    settings: '/dashboard/settings',
  },
  errors: { notFound: '/not-found' },
} as const;
